
-- 사용자 테이블
CREATE TABLE USER_INFO 
(
    "USER_ID" VARCHAR2(20 BYTE) NOT NULL,  -- 사용자ID
    "USER_NM" VARCHAR2(20 BYTE),           -- 사용자이름
    "DEPT_NM" VARCHAR2(20 BYTE),           -- 사용자이름  
    "DEPT_POSITION" VARCHAR2(20 BYTE),     -- 사용자이름
    "HP" VARCHAR2(20 BYTE),                -- 사용자이름 
    "EMP_STATUS" VARCHAR2(20 BYTE),        -- 사용자이름 
    "AUTH_YN" VARCHAR2(20 BYTE),           -- 사용자이름 
    "USE_YN" VARCHAR2(20 BYTE),            -- 사용자이름 
    "EMAIL" VARCHAR2(20 BYTE),             -- 사용자이름 
    "USER_PW" VARCHAR2(20 BYTE) NOT NULL   -- 사용자이름 
);
-- / comment on table USER_INFO is '사용자 테이블'
-- / comment on column USER_INFO.USER_ID is '일련번호'
-- / comment on column USER_INFO.USER_NM is '일련번호'
-- / comment on column USER_INFO.DEPT_NM is '사용자이름'


-- 게시판 테이블
CREATE TABLE BOARD_INFO
(
   "BOARD_IDNO" NUMBER, 
   "TITLE" VARCHAR2(255 BYTE) NOT NULL ENABLE,      -- 사용자ID
   "CONTENT" CLOB NOT NULL ENABLE,                  -- 사용자이름
   "BOARD_TYPE" VARCHAR2(100 BYTE) NOT NULL ENABLE, -- 사용자이름
   "AUTHOR" VARCHAR2(100 BYTE) NOT NULL ENABLE,     -- 사용자이름
   "RGSDE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, -- 사용자이름
   "UPDDE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, -- 사용자이름
   "VIEW_COUNT" NUMBER DEFAULT 0,                   -- 사용자이름
    PRIMARY KEY ("BOARD_IDNO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
  
-- / comment on table BOARD_INFO is '게시판 테이블'
-- / comment on column BOARD_INFO.BOARD_IDNO  is '일련번호'
-- / comment on column BOARD_INFO.USER_NM     is '일련번호'
-- / comment on column BOARD_INFO.DEPT_NM     is '사용자이름'