
Insert into USER_INFO (USER_ID,USER_NM,DEPT_NM,DEPT_POSITION,HP,EMP_STATUS,AUTH_YN,USE_YN,EMAIL,USER_PW)
  values ('egovgo','eGov시작','ICT','주임','010-1234-1234','Y','Y','Y','egovgo@k2web.co.kr','1234qwer');
  
INSERT INTO BOARD_INFO (TITLE, CONTENT, BOARD_TYPE, AUTHOR, RGSDE, UPDDE, VIEW_COUNT)
  VALUES ('글제목입니다.','글내용 입니다.','0','egovgo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,0);